const quotes = [
  "Discipline beats motivation when motivation fades.",
  "Start now, refine later.",
  "Slow progress is still progress.",
  "Consistency matters more than intensity.",
  "Focus on the process, results will follow.",
  "Small habits create big changes.",
  "Action creates clarity.",
  "Done is better than perfect.",
  "Your future self is watching.",
  "Progress, not perfection.",

  "Fear is temporary, regret lasts longer.",
  "Skill is built, not discovered.",
  "Work quietly, let results speak.",
  "One step forward is still forward.",
  "You don’t need permission to begin.",
  "The best time to start was yesterday. The next best time is now.",
  "Comfort today can cost you tomorrow.",
  "Every day is a chance to improve.",
  "Momentum is built by showing up.",
  "Hard days build strong people.",

  "You grow by doing uncomfortable things.",
  "Success is a series of small wins.",
  "Don’t wait to feel ready.",
  "Clarity comes after action.",
  "Effort compounds over time.",
  "What you repeat becomes who you are.",
  "Energy flows where focus goes.",
  "Your habits shape your future.",
  "Learning is never wasted.",
  "Patience is a form of strength.",

  "Stop overthinking. Start building.",
  "Consistency turns goals into reality.",
  "You don’t need motivation, you need systems.",
  "Little progress every day adds up.",
  "Be brave enough to be bad at first.",
  "Growth requires discomfort.",
  "If it matters, make time for it.",
  "Rest if you must, but don’t quit.",
  "Your direction matters more than your speed.",
  "Effort today creates freedom tomorrow.",

  "You are allowed to start small.",
  "Improvement is always possible.",
  "Trust the process.",
  "Show up, even on low days.",
  "The work works if you do.",
  "Future results are built today.",
  "Learn, adapt, keep going.",
  "Success favors the consistent.",
  "Your mindset shapes your reality."
]

export default quotes
